'use strict';
const crypto = require('crypto');

/** Canonical JSON: sorted keys, no incidental whitespace. Two scenario states
 *  that resolve to the same visual must serialise identically. */
function canonical(value) {
    if (value === null || typeof value !== 'object') return escapeNonAscii(JSON.stringify(value));
    if (Array.isArray(value)) return `[${value.map(canonical).join(',')}]`;
    return `{${Object.keys(value).sort()
        .map(k => `${escapeNonAscii(JSON.stringify(k))}:${canonical(value[k])}`).join(',')}}`;
}

/** The fixtures were generated by json.dumps, which escapes non-ASCII by
 *  default. Scenario prose is full of em dashes and curly quotes, so without
 *  this the JS hash diverges from the fixture key on exactly those blocks. */
function escapeNonAscii(s) {
    return s.replace(/[\u0080-\uFFFF]/g, c =>
        '\\u' + c.charCodeAt(0).toString(16).padStart(4, '0'));
}

/** The runtime cache key, and the fixture key: sha256 of the canonicalised
 *  resolved render block. Never nodeId+variantIndex - variant indices are a
 *  server-side resolution detail, and two different states can resolve to one
 *  visual. */
function cacheKey(renderBlock) {
    return crypto.createHash('sha256').update(canonical(renderBlock)).digest('hex');
}
module.exports = { cacheKey, canonical };